A02
Harshini-Jesi/Training pull request #13
Opened 2023-08-25 11:26 UTC by Harshini-Jesi

2023-08-25 12:36 UTC, meenashriTMM commented
Just saw that there are multiple commits in every branch you created. 
Why Training exercise commits are part of Academy exercise?

2023-08-28 03:23 UTC, Harshini-Jesi commented
When I want to switch between branches, I just commit the changes and then switch....That's why there are multiple commits mam.

2023-08-28 06:10 UTC, meenashriTMM requested changes

2023-08-28 06:10 UTC, meenashriTMM commented on Program.cs
> +int GetMax (Mode mode) {
Try writing this method using switch expression

2023-08-28 06:10 UTC, meenashriTMM commented on Program.cs
> +Console.WriteLine ($"Guess a number between 1 and {max}\n");
It would be more readable if you have your method implementations at the end after main program

2023-08-29 04:24 UTC, meenashriTMM approved these changes

2023-08-29 04:24 UTC, closed without merging