T22-swap indices
Harshini-Jesi/Training pull request #24
Opened 2023-09-12 11:37 UTC by Harshini-Jesi

2023-09-12 12:17 UTC, varalakshmi-imm requested changes

2023-09-12 12:17 UTC, varalakshmi-imm commented on Program.cs
> +swap (value, ref a, ref b);
Is ref required for this?

2023-09-12 12:17 UTC, varalakshmi-imm commented on Program.cs
> +void swap (char[] value, ref int a, ref int b) => (value[b], value[a]) = (value[a], value[b]);
Arrays are of reference types. Check [this ](https://stackoverflow.com/questions/967402/are-arrays-or-lists-passed-by-default-by-reference-in-c)for more info.
![image](https://github.com/Harshini-Jesi/Training/assets/75829713/63848d5f-2fcc-4a22-b448-614dea460acf)

2023-09-13 08:48 UTC, varalakshmi-imm requested changes

2023-09-13 08:48 UTC, varalakshmi-imm commented on Program.cs
> +   if (a <= value.Length && b <= value.Length) {
Not handling -ve values. If -1 is given the program crashes.

2023-09-14 07:10 UTC, varalakshmi-imm requested changes
You can also enable XML documentation for the project which enables xml type comments as that is the practice expected.
For eg:
![image](https://github.com/Harshini-Jesi/Training/assets/75829713/71138e60-bc1a-41b4-9e2c-3bce4ed36d80)

You should enable _Documentation file_ option in Build/Output in the properties of the project as shown below:
![image](https://github.com/Harshini-Jesi/Training/assets/75829713/5d75f43a-c8c6-49f5-81b4-eaed03ea1172)

2023-09-14 08:43 UTC, varalakshmi-imm requested changes

2023-09-14 08:43 UTC, varalakshmi-imm commented on Program.cs
> +      else continue;
You are returning if (condition == true) so else is not required in the next line. Just continue as if condition fails naturally the next statement will get executed.

2023-09-27 04:40 UTC, varalakshmi-imm requested changes

2023-09-27 04:40 UTC, varalakshmi-imm commented on Training.csproj
> +    <DocumentationFile>H:\harshini.s\learn\t22.txt</DocumentationFile>
![image](https://github.com/Harshini-Jesi/Training/assets/75829713/b53d81f7-0a62-4d27-8d59-d7b51beebbc0)
I am not able to compile it so leave it blank for the XML file path. Let it use the default path. Also there are warnings which have to be fixed. For XML comments, there should be class.

2023-09-27 04:40 UTC, varalakshmi-imm commented on .editorconfig.txt
> +[user]
![image](https://github.com/Harshini-Jesi/Training/assets/75829713/876563a3-3df6-46db-8af3-1cbcfe97fc3c)
Why is this .editorconfig.txt added?

2023-09-28 04:37 UTC, Harshini-Jesi commented on .editorconfig.txt
> +[user]
I have changed to Trumpf laptop, network and mail id. So, mail id and paths of notepad, winmerge and P4merge has been changed in .editorconfig file.

2023-09-28 04:43 UTC, varalakshmi-imm commented on .editorconfig.txt
> +[user]
Fine. But only one .editorconfig is required. 
If .editorconfg.txt is the new one then rename it to .editorconfig.

2023-09-28 07:41 UTC, varalakshmi-imm requested changes
Comments at the program or class level is missing.
Write what this program is doing in a couple of lines.

2023-09-28 07:41 UTC, varalakshmi-imm commented on Program.cs
> +   ///<summary>Gets the input from the user until it is a positive number</summary>
Leave a blank line before this line. In general there should be a blank line between methods or properties.

2023-09-28 07:41 UTC, varalakshmi-imm commented on Program.cs
> +   static void Swap (char[] arr, int from, int to) => (arr[to], arr[from]) = (arr[from], arr[to]);
Comments missing for this method

2023-09-28 09:19 UTC, varalakshmi-imm approved these changes

2023-09-28 09:19 UTC, varalakshmi-imm commented on Program.cs
> +   ///<param name="prompt">Displays the prompt for the user to enter the input</param>
```suggestion
   /// <param name="prompt">Displays the prompt for the user to enter the input</param>

```
@Harshini-Jesi Always leave a space after /// or //

2023-09-28 09:19 UTC, closed without merging