T23 - Voting contest
Harshini-Jesi/Training pull request #28
Opened 2023-10-06 03:30 UTC by Harshini-Jesi

2023-10-09 06:53 UTC, MetaNaveen requested changes

2023-10-09 07:14 UTC, MetaNaveen requested changes

2023-10-09 07:14 UTC, MetaNaveen commented on Program.cs
> +      foreach (char ch in input) {
Computationally costly. Requires n^2 iterations to solve the problem.

Try to use [Generic Collections](https://www.tutorialsteacher.com/csharp/csharp-collection) like Dictionary or List<(char, int)> to solve the problem more efficiently.

2023-10-09 10:48 UTC, Harshini-Jesi commented on Training.csproj
> +    <GenerateDocumentationFile>True</GenerateDocumentationFile>
Thank you!

2023-10-09 12:01 UTC, MetaNaveen requested changes
Review #2

2023-10-09 12:01 UTC, MetaNaveen commented on Program.cs
> +         if (output.TryGetValue (c, out int value)) output[c] = value + 1;
One-liner solution for the same:
output[c] = output.TryGetValue (c, out int value) ? ++value : 1;

2023-10-10 06:38 UTC, MetaNaveen requested changes
Review 3

2023-10-10 06:38 UTC, MetaNaveen commented on Program.cs
> +      while (!input.All (char.IsLetter) || input.Length == 0);
Runtime error. If I press Enter without giving any input, the code runs indefinitely.

2023-10-10 09:48 UTC, MetaNaveen approved these changes

2023-10-10 09:48 UTC, MetaNaveen commented
Working fine.

2023-10-10 09:48 UTC, closed without merging