T25-sort and swap spclchar
Harshini-Jesi/Training pull request #30
Opened 2023-10-09 12:12 UTC by Harshini-Jesi

2023-10-10 06:35 UTC, MetaNaveen requested changes
Review 1.

2023-10-10 06:35 UTC, MetaNaveen commented on Program.cs
> +      foreach (char c in arr) {
While the code is working fine, the implementation way is not as expected and computationally costly. 
The purpose of working with character array is voided.

2023-10-10 06:35 UTC, MetaNaveen commented on Program.cs
> +         Console.WriteLine (string.Join (',', result.Select (c => c)));
Unnecessary usage of Select(). You could have used just result.

2023-10-10 06:35 UTC, MetaNaveen commented on Program.cs
> +         Array.Sort (ascArr);
Instead of using Array.Sort(), you could use .Order() for code uniformity.

2023-10-10 06:35 UTC, MetaNaveen commented on Program.cs
> +      while (true) {
The if statement conditions could be put here instead of (true), with minimal changes. Avoid using 'continue' wherever possible.

2023-10-10 06:35 UTC, MetaNaveen commented on Program.cs
> +         result = new string (desArr) + result2;
Unnecessary conversion of char[] to string just for printing purpose. 

The desArr could be used directly in the string.Join() and the ToArray() can be avoided.

2023-10-20 09:48 UTC, MetaNaveen requested changes
Review 2

2023-10-20 09:48 UTC, MetaNaveen commented on Program.cs
> +      while (true) {
Could you avoid using while(true) with continue? (eg: You can use "do while")

2023-10-20 09:48 UTC, MetaNaveen commented on Program.cs
> +         arr = Console.ReadLine ().ToCharArray ();
Console.ReadLine () is of String type which is enumerable of type char that can be used in .All(). Can you find a way to avoid this conversion?

2023-10-27 10:20 UTC, Harshini-Jesi commented
Minor changes applied.

2023-10-27 10:21 UTC, MetaNaveen approved these changes

2023-10-27 10:21 UTC, MetaNaveen commented
Working fine.

2023-10-27 10:21 UTC, closed without merging