A03-Spelling bee
Harshini-Jesi/Training pull request #31
Opened 2023-10-12 09:37 UTC by Harshini-Jesi

2023-10-27 10:30 UTC, Harshini-Jesi commented
words.txt file added.

2023-10-27 10:54 UTC, MetaNaveen requested changes
**Review 1**

2023-10-27 10:54 UTC, MetaNaveen commented on Program.cs
> +   } else if (word.Length > 4) wordsAndScore.Add (word, word.Length);
Since word.Length is already checked before the loop, else if is unnecessary as it implicitly means the same.

2023-10-27 10:54 UTC, MetaNaveen commented on Program.cs
> +var sortedList = wordsAndScore.OrderByDescending (x => x.Value).ThenBy (x => x.Key).ToList ();
.ToList() could be avoided as it is used only to print.

2023-10-27 10:54 UTC, MetaNaveen commented on Program.cs
> +Console.WriteLine ($"----\n{wordsAndScore.Values.Sum ()} total");
Sum() once again iterates the dictionary to get the sum. Instead, you could use a variable to count.

2023-10-27 10:54 UTC, MetaNaveen commented on Program.cs
> +List<string> pangram = new ();
List<string> could be avoided by storing the required info to see if the word is pangram or not, within the dictionary.

2023-10-27 13:24 UTC, MetaNaveen requested changes
**Review 2**

2023-10-27 13:24 UTC, MetaNaveen commented on Program.cs
> +﻿Dictionary<string, (int score, bool IsPangram)> wordsAndScore = new ();
The naming of tuple fields could either be camelCase (preferred) or PascalCase. But has to maintain uniformity throughout the code.

2023-10-27 13:24 UTC, MetaNaveen commented on Program.cs
> +      wordsAndScore.Add (word, (word.Length + 7, true));
Can you use Ternary operator to reduce lines of code.

2023-10-31 07:39 UTC, MetaNaveen approved these changes

2023-10-31 07:40 UTC, MetaNaveen commented
Working fine.

2023-10-31 07:40 UTC, closed without merging