A7: Double.Parse
Harshini-Jesi/Training pull request #37
Opened 2023-12-12 04:19 UTC by Harshini-Jesi

2023-12-12 06:22 UTC, ravin-imm requested changes

2023-12-12 06:22 UTC, ravin-imm commented on Program.cs
> +                     sIntegral += (c - '0') * sFactorial;
Add tests for your parser.

2023-12-14 06:14 UTC, ravin-imm requested changes

2023-12-14 06:14 UTC, ravin-imm commented on Program.cs
> +            else intDouble = -1 * DoubleConvert (minus);
Please simplify these 2 checks as I see repetitive code.

2023-12-14 06:14 UTC, ravin-imm commented on Program.cs
> +         string[] dotArr = { };
Not required to create an empty array. Split (..) method will return an array.

2023-12-14 06:14 UTC, ravin-imm commented on Program.cs
> +         } else if (s.All (char.IsDigit)) foreach (char c in s) numDouble = (numDouble * 10) + (c - '0');
You are parsing through the string twice. May be when looping itself if a char is not an integer return.

2023-12-14 06:14 UTC, ravin-imm commented on Program.cs
> +            if ((s.StartsWith ('+') || s.StartsWith ('-') || s.StartsWith (dot)) && s == s[0].ToString ()) return false;
Can this be simplified as the same checks are repeated?

2023-12-15 09:44 UTC, Harshini-Jesi commented on Training.csproj
> +    <None Remove="TestT28\**" />
These files were created for testcase...... Since it was showing in the solution explorer, I removed it.

2023-12-18 10:10 UTC, ravin-imm requested changes

2023-12-18 10:10 UTC, ravin-imm commented on Program.cs
> +                     exponential = IntConvert (expower);
Can be simplified further as there is some repetition here.

2023-12-19 07:57 UTC, ravin-imm requested changes
Added some code refactoring. Check if any refactoring can be done at any other places also.

2023-12-19 07:57 UTC, ravin-imm commented on Program.cs
> +                  } else exponential = IntConvert (eArray[1]);
This can be as below using a ternary conditional operator:
`experimental = (eArray[1].StartsWith ('-') ? -1 : 1) * IntConvert (eArray[1]);`

2023-12-19 07:57 UTC, ravin-imm commented on Program.cs
> +                  } else integral = DoubleConvert (eArray[0]);
To minimize the code, use ternary conditional operator. "? :"

2023-12-19 07:57 UTC, ravin-imm commented on Program.cs
> +            }
Repititive code here:
This can be:
```
output = (result.StartsWith ('.') || result.StartsWith ('+') || result.StartsWith ('-')) ? StartCheck (result) : DoubleConvert (result);
return true;
```

2023-12-19 07:57 UTC, ravin-imm commented on Program.cs
> +            else if (s.Contains (dot) && DotCheck (s1)) return true;
This can be:
`return (s1.All (char.IsDigit) || (s.Contains (dot) && DotCheck (s1)));` 

You can return the check result itself when a boolean is returned.

2023-12-20 10:07 UTC, ravin-imm approved these changes

2023-12-20 10:07 UTC, closed without merging