T05 completed
Harshini-Jesi/Training pull request #5
Opened 2023-08-17 08:55 UTC by Harshini-Jesi

2023-08-21 11:25 UTC, meenashriTMM requested changes

2023-08-21 11:25 UTC, meenashriTMM commented on Program.cs
> +            if (IsPrime (n))
Print in a single statement using ternary operator

2023-08-21 11:25 UTC, meenashriTMM commented on Program.cs
> +            int n = int.Parse (Console.ReadLine ());
Will throw exception if input is not a number

2023-08-21 11:25 UTC, meenashriTMM commented on Program.cs
> +            for (int i = 5; i * i <= n; i += 6)
Add comments explaining your logic

2023-08-22 08:36 UTC, Harshini-Jesi commented on Program.cs
> +            for (int i = 5; i * i <= n; i += 6)
Any prime number except 2 and 3 can be represented as 6k+1 or 6k-1.....where k is a natural number. 
Hence, "for (int i = 5; i * i <= n; i += 6)" is to check the divisors.
Here, the loop starts with the next prime number after 2 and 3 i.e., 5. This will iterate with 6 at each stage until square of i is less than or equal to the given input number.
The next line of code "if (n % i == 0 || n % (i + 2) == 0)"....... 'i' represents the divisors in 6k-1 and i+2 represents the divisors in 6k+1. By checking together both the conditions, it returns whether the given number is prime or not.

2023-08-23 15:26 UTC, meenashriTMM requested changes

2023-08-24 04:21 UTC, Harshini-Jesi commented on Program.cs
> +         for (int i = 5; i * i <= n; i += 6)
if (n <= 1) return false; This line will return false i.e., not a prime number, if the given number is less than 1....i.e., negative numbers, zero and one.
if (n <= 3) return true; This will return "It is a prime number" if the given number is 2 and 3. Instead of giving n==2 || n==3, I have given this n<=3....so that for n<=1 the above condition will work and for 2 and 3, this will work.
if (n % 2 == 0 || n % 3 == 0) return false; Here, the output will be "not a prime number" if the given number is either divisible by 2 or 3. ( || represents logic OR function). % gives the reminder after division. Hence, if the reminder is zero it means it is divisible and will return false.

2023-08-24 04:43 UTC, meenashriTMM requested changes

2023-08-24 04:43 UTC, meenashriTMM commented on Program.cs
> +         for (int i = 5; i * i <= n; i += 6)
I meant adding those comments in your program as the logic of the for loop was not more evident.
If someone has to work on your code, or even if you work on your code months later, it would be difficult to understand just by looking at the code. Adding comments makes maintenance easier.
See how to add comments in C#. If you're not clear, we can have a Teams call or take help from any of the available mentors.

2023-08-24 05:47 UTC, meenashriTMM approved these changes

2023-08-24 05:47 UTC, closed without merging