T10
Harshini-Jesi/Training pull request #9
Opened 2023-08-22 09:13 UTC by Harshini-Jesi

2023-08-26 11:00 UTC, meenashriTMM requested changes

2023-08-26 11:00 UTC, meenashriTMM commented on Program.cs
> +      int h = n;
Why make a copy of variable 'h' if you could just use 'n'.
Also provide more meaningful variable names instead of h, c

2023-08-28 04:01 UTC, Harshini-Jesi commented on Program.cs
> +      int h = n;
copy variable of 'n' is made because, after the while loop is executed 'n' becomes zero. This cannot be compared with the reversed number. Hence, to retain the original number, copy of 'n' is made before the loop.

2023-08-28 05:51 UTC, meenashriTMM approved these changes

2023-08-28 05:51 UTC, closed without merging